config/routes.rb
Rails.application.routes.draw do
  
	root 'beta#home'

	get 'search' => 'beta#results', as:'search'

	get 'login' => 'beta#login', as:'login'

	get 'register' => 'beta#register', as:'register'

	post 'login' => 'beta#login_submit', as:'login_submit'

	match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    match 'auth/failure', to: redirect('/'), via: [:get, :post]
    match 'signout', to: 'sessions#signout', as: 'signout', via: [:get, :post]

	resources :packages
	resources :customers
	resources :caterers
end

app/controllers/beta_controller.rb
class BetaController < ApplicationController

	def home
		@events = ['Wedding', 'Debut', 'Birthday - Kids', 'Birthday - Teens', 'Birthday - Adults', 'Birthday - Senior Citizens', 'Baptismal', 'Promenade'] #CHANGE WHEN ADDING CATEGORIES
		@events = @events.sort_by!{ |c| c.downcase }
		@locations = ['Bulacan','Cavite','Laguna','Metro Manila','Tagaytay'] #CHANGE WHEN ADDING LOCATIONS
		cookies.delete(:package_id)
	end

	def results
		@results = Package.all
		@results = @results.where('category LIKE ?', "%" + params[:search][:event] + "%") if params[:search][:event]
		@results = @results.paginate(:page => params[:page], :per_page => 12)
		# EVENTS AND LOCATIONS AVAILABLE
		@events = ['Wedding', 'Debut', 'Birthday - Kids', 'Birthday - Teens', 'Birthday - Adults', 'Birthday - Senior Citizens', 'Baptismal', 'Promenade'] #CHANGE WHEN ADDING CATEGORIES
		@events = @events.sort_by!{ |c| c.downcase }
		@locations = ['Bulacan','Cavite','Laguna','Metro Manila','Tagaytay'] #CHANGE WHEN ADDING LOCATIONS
	end

	def login
		if session[:caterer_id].present? && params[:p].present?
			session[:caterer_id] = nil
			cookies[:package_id] = params[:p]
		else
			if session[:caterer_id].present? || session[:caterer_id].present?
				flash[:danger] = "Logged in already."
				redirect_to beta_path
			end
		end
	end

	def register
		if session[:customer_id].present?
			session[:customer_id] = nil
		elsif session[:caterer_id].present?
			redirect_to caterer_path(Caterer.find(session[:caterer_id]).uid)
		else
		end
	end

	def login_submit
		if Caterer.where(mobile_1: login_params[:mobile]).present?
			@caterer = Caterer.find_by(mobile_1: login_params[:email])
			if login_params[:password] == @caterer.password
				session[:caterer_id] = @caterer.id
				if cookies[:package_id].present?
					redirect_to package_path(cookies[:package_id])
				else
					redirect_to caterer_path(@caterer.uid)
				end
			else
				flash[:danger] = 'Invalid Email, Phone or Password'
				redirect_to login_path(:u => 'caterer')
			end
		else
			flash[:danger] = 'Invalid Email, Phone or Password'
			redirect_to login_path(:u => 'caterer')
		end
	end

	private def login_params
		params.require(:login).permit(:mobile, :password)
	end
end

app/helpers/beta_helper.rb
module BetaHelper
end

app/views/beta/home.html.erb
<div class="beta-main">
	<div class="beta-nav">
		<div class="beta-nav-anchors">
			<% if session[:customer_id].present? %>
			<button style="color:white;" class="beta-nav-anchor beta-nav-login" onclick="window.location.href = '/agencies/<%= Agency.find(session[:customer_id]).uid %>';">Profile</button>
			<button style="color:white;" class="beta-nav-anchor" onclick="window.location.href = '/signout';">Log Out</button>
			<% elsif session[:caterer_id].present? %>
			<button style="color:white;" class="beta-nav-anchor beta-nav-login" onclick="window.location.href = '/travellers/<%= Traveller.find(session[:caterer_id]).uid %>';">Profile</button>
			<button style="color:white;" class="beta-nav-anchor" onclick="window.location.href = '/signout';">Log Out</button>
			<% else %>
			<button style="color:white;" class="beta-nav-anchor" onclick="anchor('how_it_works');">How It Works</button>
			<button style="color:white;" class="beta-nav-anchor" onclick="anchor('about');">About</button>
			<button style="color:white;" class="beta-nav-anchor" onclick="anchor('contact_us');">Contact Us</button>
			<button style="color:white;" class="beta-nav-anchor beta-nav-register" onclick="window.location.href = '/register';">List Your Catering</button>
			<button style="color:white;" class="beta-nav-anchor beta-nav-login" onclick="window.location.href = '/login';">Log In</button>
			<% end %>
		</div>
	</div>
	<div class="beta-main-content">
		<h1 class="beta-main-logo">CaterX</h1>
		<h3 class="beta-main-mantra">Find Catering Services In an Instant</h3>
		<%= form_for :search, namespace: 'beta', :method => 'get', url: search_path do |f| %>
		<div class="beta-main-search-inputs">
			<div class="beta-main-search-destination beta-main-search-input">
				<p class="beta-main-search-input-label">TYPE OF EVENT</p>
				<%= f.select :event, options_for_select(@events) %>
			</div>
			<div class="beta-main-search-submit">
				<button type="submit">Search</button>
			</div>
		</div>
		<% end %>
	</div>
</div>
<script type="text/javascript">
function anchor(section) {
	window.location.hash = section;
}
</script>

app/views/beta/login.html.erb
<div class="beta-login-inputs">
  <h3 class="beta-register-header">Login</h3>
  <h5 class="beta-register-sub" id="beta-login-paragraph-customer">Login to CaterX to access catering packages<br>that fit your budget and needs.</h5>
  <h5 class="beta-register-sub" id="beta-login-paragraph-caterer" style="display:none;">Login to CaterX to reach more customers<br>and boost your sales.</h5>
  <div id="beta-login-customer">
    <button class="beta-login-facebook" onclick="window.location.href = '/auth/facebook/';" type="button">Continue With Facebook</button>
    <button class="beta-login-caterer-btn" onclick="caterer();" type="button">Catering Service Login</button>
  </div>
  <div id="beta-login-caterer" style="display:none;">
    <%= form_for :login, namespace: 'beta', :method => 'post', url: login_submit_path do |f| %>
    <div class="beta-login-email beta-login-input">
      <p class="beta-login-input-label">MOBILE NUMBER</p>
      <%= f.text_field :mobile, placeholder: "Mobile Number", :required => 'required' %>
    </div>
    <div class="beta-login-password beta-login-input">
      <p class="beta-login-input-label">PASSWORD</p>
      <%= f.password_field :password, placeholder: "Password" %>
    </div>
    <div class="beta-login-submit">
      <button type="submit">Log In</button>
    </div>
    <% end %>
    <div class="beta-login-escape">
      <p>Not a catering service? <button onclick="customer();" type="button">Login as Customer</button></p>
    </div>
  </div>
</div>
<script>
function caterer() {
document.getElementById('beta-login-paragraph-customer').style.display = "none";
document.getElementById('beta-login-paragraph-caterer').style.display = "block";
document.getElementById('beta-login-caterer').style.display = "block";
document.getElementById('beta-login-customer').style.display = "none";
}
function customer() {
document.getElementById('beta-login-paragraph-caterer').style.display = "none";
document.getElementById('beta-login-paragraph-customer').style.display = "block";
document.getElementById('beta-login-caterer').style.display = "none";
document.getElementById('beta-login-customer').style.display = "block";
}
if (window.location.href.split('?u=')[1] == "caterer") {
setTimeout(caterer, 25);
}
</script>

app/views/beta/register.html.erb
<div class="beta-register-inputs">
	<h3 class="beta-register-header">Register</h3>
	<h5 class="beta-register-sub">Join CaterX in making unforgettable events<br> and start boosting your sales.</h5>
	<%= form_for :caterer, namespace: 'beta', :method => 'post', url: caterers_path do |f| %>
	<div class="beta-register-email beta-register-input">
		<p class="beta-register-input-label">NAME OF CATERING SERVICE</p>
		<%= f.text_field :name, placeholder: "Name of Catering Service", :required => 'required' %>
	</div>
	<div class="beta-register-email beta-register-input">
		<p class="beta-register-input-label">MOBILE NUMBER</p>
		<%= f.text_field :mobile_1, placeholder: "09123456789", :required => 'required', maxlength: 11 %>
	</div>
	<div class="beta-register-password beta-register-input">
		<p class="beta-register-input-label">PASSWORD</p>
		<%= f.password_field :password, placeholder: "Password", :onkeyup => 'check(this);' %>
	</div>
	<div class="beta-register-password beta-register-input">
		<p class="beta-register-input-label">CONFIRM PASSWORD</p>
		<input placeholder="Confirm Password" onkeyup="check(this);match();" type="password" id="beta_agency_confirm_password">
	</div>
	<div class="beta-register-submit">
		<button type="submit" id="beta-register-submit-button">Register</button>
	</div>
	<% end %>
	<div class="beta-register-escape">
		<p>Already have an account? <button onclick="window.location.href = '/login?u=caterer';" type="button">Login</button></p>
	</div>
</div>

app/views/beta/results.html.erb
<%= form_for :search, namespace: 'beta', :method => 'get', url: search_path do |f| %>
<div class="beta-main-search-inputs">
	<div class="beta-main-search-destination beta-main-search-input">
		<p class="beta-main-search-input-label">TYPE OF EVENT</p>
		<%= f.select :event, options_for_select(@events) %>
	</div>
	<div class="beta-main-search-submit">
		<button type="submit">Search</button>
	</div>
</div>
<% end %>
<div class="beta-results-packages">
	<% @results.shuffle.each do |p| %>
	<% if session[:customer_id].present? %>
	<% p.increment!(:appearances, 1) %>
	<% end %>
	<a href="/packages/<%= p.id %>" target="blank" style="text-decoration:none;color:white;"><%= p.name %></a>
	<% end %>
</div>
<div class="beta-results-paginate">
	<%= will_paginate @results %>
</div>